# Use a base image
FROM ubuntu:22.04

LABEL maintainer="docker@kraft6.com"

#For TZ data blocking the run
ENV TZ=Asia/Kolkata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install necessary packages and dependencies
RUN apt-get update && apt-get install -y \
    nginx \
    php-fpm \
    php-apcu \
    php-gd \
    php-imap \
    php-ldap \
    php-curl \
    php-mysql \
    php-xml \
    php-mbstring \
    php-bcmath \
    php-intl \
    php-bz2 php-zip \
    unzip \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Download GLPI and extract it
RUN wget -O /tmp/glpi.tar.gz https://github.com/glpi-project/glpi/releases/download/10.0.11/glpi-10.0.11.tgz && \
    tar -xzf /tmp/glpi.tar.gz -C /var/www/html/ && \
    rm /tmp/glpi.tar.gz && \
    chown -R www-data:www-data /var/www/html/glpi

# Copy NGINX configuration file
COPY nginx-glpi.conf /etc/nginx/sites-available/default

COPY entrypoint-prebuilt.sh /tmp/

# Expose ports
EXPOSE 8888

# Start services
ENTRYPOINT /tmp/entrypoint-prebuilt.sh
