version: '1.1'
name: 'kraftsix-glpi-v2'

services:
  mariadb:
    image: mariadb
    restart: always
    networks:
      - gnetwork
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_NAME}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ${MARIADB_FILES}:/var/lib/mysql
    env_file:
      - .env

  server:
    image: kraftsix/glpi:${KRAFTSIX_GLPI_TAG}
    restart: always
    networks:
      - gnetwork
    ports:
      - "${GLPI_PORT}:8888"
    depends_on:
      - mariadb
    volumes:
      - ${GLPI_STORAGE}:/var/www/html/glpi
    env_file:
      - .env
    environment:
      TZ: ${TZDATA_TIMEZONE:-Asia/Kolkata}

networks:
  gnetwork:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"